### ISSUE TITLE
Support for axios 1.x

### ISSUE THREAD

**Issue by jeremyVignelles** [Toilal/auth-toolbox#25]
Hello,

This package currently requires axios v0.21.1 as a peerDependency. It would be nice to upgrade this dependency to 1.x (1.2.1 being the latest at the time of writing).

This would allow us to upgrade the axios version on our side.

**Comment by Toilal** [comment]
Please let me know if you have any integration issue of v7.0.0

**Comment by jeremyVignelles** [comment]
Seems OK on our side, thanks 🙂
